### ISSUE TITLE
dev-4.x: 2 issues found on testnet

### ISSUE THREAD

**Issue by cydg** [syscoin/sentinel#7]
https://github.com/syscoin/sentinel/blob/62e1b41bfa49e12888c32ddf03ffca1f28f3a4ce/lib/base58.py#L119
gives  a warning and should be
```    assert get_bcaddress_version('15VjRaDX9zpbA8LVnbrCAFzrVzN7ixHNsC') == 0```
(as it is in syscoin/contrib/testgen/base58.py)

https://github.com/syscoin/sentinel/blob/62e1b41bfa49e12888c32ddf03ffca1f28f3a4ce/lib/syscoin_config.py#L31
```        match = re.findall(r'^rpc(user|password|port)=(.*?)$', data, re.MULTILINE)```
so the match does not find lines like "gethrpcport=..." in syscoin.conf

**Comment by sidhujag** [comment]
@willyko can you fix
